package Classes;

import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Collator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {
    //Realiza la conexión a la BD
    Conexion conexion;
    /**
     * Creates new form Interfaz
     */
    private Point point;
    
    public Interfaz() {
        conexion = new Conexion("barraganthebarbers");
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        CampoO1.setVisible(false);//Campos obligatorios
        CampoO2.setVisible(false);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icono1.png")); //Carga miniatura
        return retValue;
    }
    
    public boolean Validar(){
        int contV = 0;
                
        if(LeerUsuario.getText().equals(""))
            CampoO1.setVisible(true);
        else{
            CampoO1.setVisible(false);
            contV+=1;
        }
        String passU = "";
        char []password = LeerContraseña.getPassword();
        int tamanio = password.length;
        for(int x = 0; x<tamanio; x++){
            passU+=password[x];
        }
        if(passU.equals(""))
            CampoO2.setVisible(true);
        else{
            CampoO2.setVisible(false);
            contV+=1;
        }
        
        return contV == 2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonRegistrarse = new javax.swing.JButton();
        Icono = new javax.swing.JLabel();
        TextoContraseña = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JLabel();
        LeerUsuario = new javax.swing.JTextField();
        BotonLogIn = new javax.swing.JButton();
        LeerContraseña = new javax.swing.JPasswordField();
        CampoO1 = new javax.swing.JLabel();
        CampoO2 = new javax.swing.JLabel();
        BotonSecretaria = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        BotonMinimizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(560, 620));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonRegistrarse.setBackground(new java.awt.Color(212, 172, 13));
        BotonRegistrarse.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        BotonRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo Usuario2.png"))); // NOI18N
        BotonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 80, 50));

        Icono.setBackground(new java.awt.Color(255, 204, 255));
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoDeInicio2.png"))); // NOI18N
        jPanel1.add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 260, -1));

        TextoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        TextoContraseña.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        TextoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        TextoContraseña.setText("Contraseña:");
        jPanel1.add(TextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 150, 40));

        TextoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        TextoUsuario.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        TextoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TextoUsuario.setText("Usuario:");
        jPanel1.add(TextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 110, 40));

        LeerUsuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LeerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(LeerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 250, 40));

        BotonLogIn.setBackground(new java.awt.Color(212, 172, 13));
        BotonLogIn.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        BotonLogIn.setForeground(new java.awt.Color(255, 255, 255));
        BotonLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login_1.png"))); // NOI18N
        BotonLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLogInActionPerformed(evt);
            }
        });
        jPanel1.add(BotonLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 120, 40));
        BotonLogIn.getAccessibleContext().setAccessibleDescription("");

        LeerContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(LeerContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 250, 40));

        CampoO1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CampoO1.setText("*Campo Obligatorio");
        jPanel1.add(CampoO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 140, 20));

        CampoO2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CampoO2.setText("*Campo Obligatorio");
        jPanel1.add(CampoO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 20));

        BotonSecretaria.setBackground(new java.awt.Color(212, 172, 13));
        BotonSecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Monitor.png"))); // NOI18N
        BotonSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSecretariaActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 130, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 640));

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jPanel2AncestorResized(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setBackground(new java.awt.Color(203, 67, 53));
        BotonSalir.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.png"))); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        jPanel2.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 70, -1));

        BotonMinimizar.setBackground(new java.awt.Color(95, 106, 106));
        BotonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimize_1.png"))); // NOI18N
        BotonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMinimizarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoBarragan48px.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarseActionPerformed
        conexion.Desconectar();
        InterfazRegistrarse vIR = new InterfazRegistrarse();
        vIR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegistrarseActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        conexion.Desconectar();
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void LeerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerUsuarioActionPerformed

    }//GEN-LAST:event_LeerUsuarioActionPerformed

    private void LeerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerContraseñaActionPerformed
        
    }//GEN-LAST:event_LeerContraseñaActionPerformed

    private void BotonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLogInActionPerformed
        if(Validar() == true){
            
            try {
                Statement st;
                ResultSet rs;
                
                int id;
                String nombreU = LeerUsuario.getText();
                String passU = "";
                char []password = LeerContraseña.getPassword();
                int tamanio = password.length;
                for(int x = 0; x<tamanio; x++){
                    passU+=password[x];
                }
                
                boolean bandera = false;//Para verificar que existe un usuario con ese nombre
                st = conexion.cx.createStatement();
                rs = st.executeQuery("Select * From barberos");
                
                Collator comparador = Collator.getInstance();
                comparador.setStrength(Collator.PRIMARY);
                while (bandera == false && rs.next()){
                    id = rs.getInt("id_barbero");
                    if(comparador.equals(rs.getString("nombre_usuario"),nombreU)){
                        bandera = true;
                        if(comparador.equals(rs.getString("contraseña"),passU)){
                            if(rs.getString("tipo_u").equals("Administrador")){
                                conexion.Desconectar();
                                InterfazAdmin vIA = new InterfazAdmin();
                                vIA.setVisible(true);
                                this.setVisible(false);
                            }else{
                                conexion.Desconectar();
                                InterfazBarbero vIB = new InterfazBarbero();
                                vIB.setBarbero(id, nombreU);
                                vIB.setVisible(true);
                                this.setVisible(false);
                            }
                        }else
                            JOptionPane.showMessageDialog(null,"Contraseña Incorrecta");
                        break;
                    }
                }
                if(bandera == false)
                    JOptionPane.showMessageDialog(null,"Usuario: "+nombreU+" INEXISTENTE");
            } catch (SQLException ex) {
                Logger.getLogger(InterfazRegistrarse.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_BotonLogInActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel2AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel2AncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorResized

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        point = evt.getPoint();
        getComponentAt(point);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int CurrentX = this.getLocation().x;
        int CurrentY = this.getLocation().y;
        
        int MoveX = (CurrentX + evt.getX()) - (CurrentX + point.x);
        int MoveY = (CurrentY + evt.getY()) - (CurrentY + point.y);
        
        int x = CurrentX + MoveX;
        int y = CurrentY + MoveY;
        
        this.setLocation(x,y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void BotonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonMinimizarActionPerformed

    private void BotonSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSecretariaActionPerformed
        conexion.Desconectar();
        InterfazSecre vIS = new InterfazSecre();
        vIS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonSecretariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogIn;
    private javax.swing.JButton BotonMinimizar;
    private javax.swing.JButton BotonRegistrarse;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonSecretaria;
    private javax.swing.JLabel CampoO1;
    private javax.swing.JLabel CampoO2;
    private javax.swing.JLabel Icono;
    private javax.swing.JPasswordField LeerContraseña;
    private javax.swing.JTextField LeerUsuario;
    private javax.swing.JLabel TextoContraseña;
    private javax.swing.JLabel TextoUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
