package Classes;

import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.text.Collator;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class InterfazRegistrarse extends javax.swing.JFrame {
    //Realiza la conexión a la BD
    Conexion conexion;
    
    private Point point;
    
    public InterfazRegistrarse() {
        conexion = new Conexion("barraganthebarbers");
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        restringeNumeros(LeerEdad);
        restringeChars(LeerNombres);
        restringeChars(LeerApellidos);
        CampoO1.setVisible(false);//Campos obligatorios
        CampoO2.setVisible(false);
        CampoO3.setVisible(false);
        CampoO4.setVisible(false);
        CampoO5.setVisible(false);
        CampoO6.setVisible(false);
        CampoO7.setVisible(false);
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icono1.png")); //Carga miniatura
        return retValue;
    }
    
    public boolean Validar(){
        int contV = 0;
                
        if(LeerNombreDeUsuario.getText().equals(""))
            CampoO1.setVisible(true);
        else{
            CampoO1.setVisible(false);
            contV+=1;
        }
        String passU = "";
        char []password = LeerContraseña.getPassword();
        int tamanio = password.length;
        for(int x = 0; x<tamanio; x++){
            passU+=password[x];
        }
        if(passU.equals(""))
            CampoO2.setVisible(true);
        else{
            CampoO2.setVisible(false);
            contV+=1;
        }
        if(LeerNombres.getText().equals(""))
            CampoO3.setVisible(true);
        else{
            CampoO3.setVisible(false);
            contV+=1;
        }
        if(LeerApellidos.getText().equals(""))
            CampoO4.setVisible(true);
        else{
            CampoO4.setVisible(false);
            contV+=1;
        }
        if(LeerEdad.getText().equals(""))
            CampoO5.setVisible(true);
        else{
            CampoO5.setVisible(false);
            contV+=1;
        }
        if(LeerDireccion.getText().equals(""))
            CampoO6.setVisible(true);
        else{
            CampoO6.setVisible(false);
            contV+=1;
        }
        if(LeerTipoDeUsuario.getSelectedItem().toString().equals("..."))
            CampoO7.setVisible(true);
        else{
            CampoO7.setVisible(false);
            contV+=1;
        }
        
        return contV == 7;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TextoUsuario = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        TextoNombreDeUsuario = new javax.swing.JLabel();
        LeerNombreDeUsuario = new javax.swing.JTextField();
        TextoContraseña = new javax.swing.JLabel();
        TextoNombres = new javax.swing.JLabel();
        TextoApellidos = new javax.swing.JLabel();
        TextoEdad = new javax.swing.JLabel();
        TextoDireccion = new javax.swing.JLabel();
        TextoTipoDeUsuario = new javax.swing.JLabel();
        LeerContraseña = new javax.swing.JPasswordField();
        LeerNombres = new javax.swing.JTextField();
        LeerApellidos = new javax.swing.JTextField();
        LeerEdad = new javax.swing.JTextField();
        LeerDireccion = new javax.swing.JTextField();
        LeerTipoDeUsuario = new javax.swing.JComboBox<>();
        BotonRegistrarse = new javax.swing.JButton();
        CampoO1 = new javax.swing.JLabel();
        CampoO2 = new javax.swing.JLabel();
        CampoO3 = new javax.swing.JLabel();
        CampoO4 = new javax.swing.JLabel();
        CampoO5 = new javax.swing.JLabel();
        CampoO6 = new javax.swing.JLabel();
        CampoO7 = new javax.swing.JLabel();
        Comentario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(560, 620));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setBackground(new java.awt.Color(203, 67, 53));
        BotonSalir.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.png"))); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        jPanel2.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 30));

        jButton1.setBackground(new java.awt.Color(95, 106, 106));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimize_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoBarragan48px.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 50);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(410, 545));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 545));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoUsuario.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        TextoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TextoUsuario.setText("REGISTRO");
        jPanel1.add(TextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 220, 50));

        BotonInicio.setBackground(new java.awt.Color(154, 125, 10));
        BotonInicio.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Arrow left.png"))); // NOI18N
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        jPanel1.add(BotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 60, 30));

        TextoNombreDeUsuario.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TextoNombreDeUsuario.setText("Nombre de Usuario");
        jPanel1.add(TextoNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 170, 30));

        LeerNombreDeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerNombreDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerNombreDeUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(LeerNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 200, 30));

        TextoContraseña.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TextoContraseña.setText("Contraseña");
        jPanel1.add(TextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, 30));

        TextoNombres.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TextoNombres.setText("Nombre (s)");
        jPanel1.add(TextoNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 30));

        TextoApellidos.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TextoApellidos.setText("Apellido (s)");
        jPanel1.add(TextoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 110, 30));

        TextoEdad.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TextoEdad.setText("Edad (años)");
        jPanel1.add(TextoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 110, 30));

        TextoDireccion.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TextoDireccion.setText("Dirección");
        jPanel1.add(TextoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 110, 30));

        TextoTipoDeUsuario.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TextoTipoDeUsuario.setText("Tipo de Usuario");
        jPanel1.add(TextoTipoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 140, 30));

        LeerContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(LeerContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 200, 30));

        LeerNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerNombresActionPerformed(evt);
            }
        });
        jPanel1.add(LeerNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 30));

        LeerApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(LeerApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 200, 30));

        LeerEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerEdadActionPerformed(evt);
            }
        });
        jPanel1.add(LeerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 200, 30));

        LeerDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(LeerDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 200, 30));

        LeerTipoDeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LeerTipoDeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Barbero" }));
        LeerTipoDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerTipoDeUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(LeerTipoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 200, 30));

        BotonRegistrarse.setBackground(new java.awt.Color(154, 125, 10));
        BotonRegistrarse.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        BotonRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Palomita.png"))); // NOI18N
        BotonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 60, 30));

        CampoO1.setText("*Campo Obligatorio");
        jPanel1.add(CampoO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 110, 20));

        CampoO2.setText("*Campo Obligatorio");
        jPanel1.add(CampoO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, -1));

        CampoO3.setText("*Campo Obligatorio");
        jPanel1.add(CampoO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, -1));

        CampoO4.setText("*Campo Obligatorio");
        jPanel1.add(CampoO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 110, -1));

        CampoO5.setText("*Campo Obligatorio");
        jPanel1.add(CampoO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 110, -1));

        CampoO6.setText("*Campo Obligatorio");
        jPanel1.add(CampoO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 110, -1));

        CampoO7.setText("*Seleccione una opcion");
        jPanel1.add(CampoO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 130, -1));

        Comentario1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        Comentario1.setText("Verifique que todos los campos sean correctos");
        jPanel1.add(Comentario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 390, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 560, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        conexion.Desconectar();
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        conexion.Desconectar();
        Interfaz vI = new Interfaz();
        vI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void LeerNombreDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerNombreDeUsuarioActionPerformed

    }//GEN-LAST:event_LeerNombreDeUsuarioActionPerformed

    private void LeerTipoDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerTipoDeUsuarioActionPerformed
              
    }//GEN-LAST:event_LeerTipoDeUsuarioActionPerformed

    private void LeerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerContraseñaActionPerformed
       
    }//GEN-LAST:event_LeerContraseñaActionPerformed

    private void LeerNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerNombresActionPerformed
        
    }//GEN-LAST:event_LeerNombresActionPerformed

    private void LeerApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerApellidosActionPerformed
       
    }//GEN-LAST:event_LeerApellidosActionPerformed

    private void LeerEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerEdadActionPerformed
       
    }//GEN-LAST:event_LeerEdadActionPerformed

    private void LeerDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerDireccionActionPerformed
        
    }//GEN-LAST:event_LeerDireccionActionPerformed

    private void BotonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarseActionPerformed
        if(Validar() == true){
            if(JOptionPane.showInternalConfirmDialog(null, "¿Confirmar Registro?") == 0){
                try {
                    Statement st;
                    ResultSet rs;

                    String nombreU = LeerNombreDeUsuario.getText();
                    String nombresU = LeerNombres.getText();
                    String apellidosU = LeerApellidos.getText();
                    Integer edadU = Integer.valueOf(LeerEdad.getText());
                    String direccionU = LeerDireccion.getText();
                    String tipoU = LeerTipoDeUsuario.getSelectedItem().toString();

                    String passU = "";
                    char []password = LeerContraseña.getPassword();
                    int tamanio = password.length;
                    for(int x = 0; x<tamanio; x++){
                        passU+=password[x];
                    }

                    boolean bandera = false;//Para verificar que los datos no sean repetidos
                    st = conexion.cx.createStatement();
                    rs = st.executeQuery("Select * From barberos");
                    Collator comparador = Collator.getInstance();
                    comparador.setStrength(Collator.PRIMARY);
                    String aux;
                    while (rs.next() && bandera == false){
                        aux =rs.getString("nombre_usuario");
                        if(comparador.equals(aux, nombreU)){
                            bandera = true;
                            JOptionPane.showMessageDialog(null,"Usuario: "+nombreU+" ya existe.");
                        }
                    }
                    if(bandera == false){//Para ingresar el nuevo usuario
                        PreparedStatement pps = conexion.cx.prepareStatement("INSERT INTO barberos(nombre_usuario,contraseña,nombres,apellidos,edad,direccion,tipo_u) VALUES(?,?,?,?,?,?,?)");
                        pps.setString(1,nombreU);
                        pps.setString(2, passU);
                        pps.setString(3, nombresU);
                        pps.setString(4, apellidosU);
                        pps.setInt(5, edadU);
                        pps.setString(6,direccionU);
                        pps.setString(7, tipoU);
                        pps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Registro Guardado.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazRegistrarse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_BotonRegistrarseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        point = evt.getPoint();
        getComponentAt(point);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int CurrentX = this.getLocation().x;
        int CurrentY = this.getLocation().y;
        
        int MoveX = (CurrentX + evt.getX()) - (CurrentX + point.x);
        int MoveY = (CurrentY + evt.getY()) - (CurrentY + point.y);
        
        int x = CurrentX + MoveX;
        int y = CurrentY + MoveY;
        
        this.setLocation(x,y);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistrarse().setVisible(true);
            }
        });
    }
    
    
    private void restringeNumeros(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(!Character.isDigit(c)){
                    e.consume();
                }
            }
        });
    }
    
    private void restringeChars(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(!Character.isLetter(c) && !Character.isSpaceChar(c)){
                    e.consume();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonRegistrarse;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel CampoO1;
    private javax.swing.JLabel CampoO2;
    private javax.swing.JLabel CampoO3;
    private javax.swing.JLabel CampoO4;
    private javax.swing.JLabel CampoO5;
    private javax.swing.JLabel CampoO6;
    private javax.swing.JLabel CampoO7;
    private javax.swing.JLabel Comentario1;
    private javax.swing.JTextField LeerApellidos;
    private javax.swing.JPasswordField LeerContraseña;
    private javax.swing.JTextField LeerDireccion;
    private javax.swing.JTextField LeerEdad;
    private javax.swing.JTextField LeerNombreDeUsuario;
    private javax.swing.JTextField LeerNombres;
    private javax.swing.JComboBox<String> LeerTipoDeUsuario;
    private javax.swing.JLabel TextoApellidos;
    private javax.swing.JLabel TextoContraseña;
    private javax.swing.JLabel TextoDireccion;
    private javax.swing.JLabel TextoEdad;
    private javax.swing.JLabel TextoNombreDeUsuario;
    private javax.swing.JLabel TextoNombres;
    private javax.swing.JLabel TextoTipoDeUsuario;
    private javax.swing.JLabel TextoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
